version: '3'
services:
  mongo-test:
    container_name: mongo-test
    #hostname: mongo-test
    image: mongo
    ports:
      - 7000:27017
    volumes:
      - mongodb:/data/db
      - ./mongo.conf:/etc/mongo.conf
    command: ["-f", "/etc/mongo.conf"]

volumes:
  mongodb: