version: '3'
services:
  mongo-test:
    container_name: mongo-test
    #hostname: mongo-test
    image: mongo
    ports:
      - 7000:27017
    volumes:
      - mongodb:/data/db
      - ./mongo.conf:/etc/mongo.conf
      - ./importRecipes.json:/mongo-seed/importRecipes.json
      - ./importUsers.json:/mongo-seed/importUsers.json
      - ./init-db.js:/mongo-seed/init-db.js
      - ../scripts/init-import-data.sh:/scripts/init-import-data.sh
    command: ["-f", "/etc/mongo.conf"]

volumes:
  mongodb: